version: "3.9"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    networks: 
      - warrior
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["--label-enable", "--cleanup", "--interval", "3600"]
  docker-cli:
    container_name: docker-cli
    image: docker:cli
    networks: 
      - warrior
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["/bin/sh", "-c", "while true; do sleep 30m; docker restart reddit-warrior; done"]
  reddit-warrior:
    container_name: reddit-warrior
    image: atdr.meo.ws/archiveteam/reddit-grab
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks: 
      - warrior
    restart: unless-stopped
    depends_on:
      - watchtower
      - docker-cli
    command: ["--concurrent", "${CONCURRENT}", "${USERNAME}"]

networks:
  warrior:
    name: warrior
    driver: bridge
